/**
 * Generate print-ready A4 PDFs for marker placement sheets.
 * Supports N markers with dynamic numbering.
 */
import jsPDF from "jspdf";
import QRCode from "qrcode";
import { generateMarkerCanvas } from "@/lib/generateMarkers";
import { type MarkerPoint, getSafeMarkerColor, hexToRgb } from "@/lib/markerTypes";

const A4_W = 210;
const A4_H = 297;
const MARGIN = 15;

export async function generateMarkerPDF(
  marker: MarkerPoint,
  projectName: string,
  shareUrl: string
): Promise<jsPDF> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const color = getSafeMarkerColor(marker.index);
  const [cr, cg, cb] = hexToRgb(color.bg);
  const contentW = A4_W - MARGIN * 2;
  let y = MARGIN;

  // Header bar
  doc.setFillColor(cr, cg, cb);
  doc.rect(0, 0, A4_W, 18, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(projectName.toUpperCase(), MARGIN, 12);
  doc.text(`MARKER ${marker.index}`, A4_W - MARGIN, 12, { align: "right" });

  y = 26;

  // Point label
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(`Point ${marker.index} — ${marker.label || `Marker ${marker.index}`}`, A4_W / 2, y, { align: "center" });
  y += 10;

  // Marker image
  const markerCanvas = generateMarkerCanvas(marker, projectName);
  const markerDataUrl = markerCanvas.toDataURL("image/png");
  const markerSize = 130;
  const markerX = (A4_W - markerSize) / 2;
  doc.addImage(markerDataUrl, "PNG", markerX, y, markerSize, markerSize);
  y += markerSize + 8;

  // Coordinates
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("PLACEMENT COORDINATES", A4_W / 2, y, { align: "center" });
  y += 6;

  doc.setFontSize(13);
  doc.setFont("courier", "bold");
  doc.setTextColor(40, 40, 40);
  doc.text(`X: ${marker.x}    Y: ${marker.y}    Z: ${marker.z}  (mm)`, A4_W / 2, y, { align: "center" });
  y += 10;

  // QR code
  const qrCanvas = document.createElement("canvas");
  await QRCode.toCanvas(qrCanvas, shareUrl, { width: 400, margin: 1, color: { dark: "#212121", light: "#FFFFFF" } });
  const qrDataUrl = qrCanvas.toDataURL("image/png");
  const qrSize = 32;
  doc.addImage(qrDataUrl, "PNG", (A4_W - qrSize) / 2, y, qrSize, qrSize);
  y += qrSize + 4;

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(140, 140, 140);
  doc.text("Scan to view AR experience", A4_W / 2, y, { align: "center" });
  y += 4;
  doc.setFontSize(7);
  doc.text(shareUrl, A4_W / 2, y, { align: "center" });
  y += 8;

  // Instructions footer
  doc.setDrawColor(220, 220, 220);
  doc.line(MARGIN, y, A4_W - MARGIN, y);
  y += 5;

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(80, 80, 80);
  doc.text("PLACEMENT INSTRUCTIONS", MARGIN, y);
  y += 5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 100, 100);
  const instructions = [
    `1. Print this page at 100% scale (no fit-to-page). The marker must be actual size for accurate AR tracking.`,
    `2. Place this sheet at the coordinates shown above (X: ${marker.x}, Y: ${marker.y}, Z: ${marker.z} mm).`,
    `3. Ensure the marker is flat, well-lit, and unobstructed. Avoid reflective surfaces or glass overlays.`,
    `4. At least 3 markers must be placed before the AR experience can align the 3D model.`,
  ];
  instructions.forEach((line) => {
    const split = doc.splitTextToSize(line, contentW);
    doc.text(split, MARGIN, y);
    y += split.length * 3.5 + 1.5;
  });

  doc.setFontSize(6.5);
  doc.setTextColor(180, 180, 180);
  doc.text("Generated by Archi AR", A4_W / 2, A4_H - 8, { align: "center" });

  return doc;
}

/** Generate and trigger download of a single marker PDF. */
export async function downloadMarkerPDF(
  marker: MarkerPoint,
  projectName: string,
  shareUrl: string
): Promise<void> {
  const doc = await generateMarkerPDF(marker, projectName, shareUrl);
  const safeName = projectName.replace(/\s+/g, "_");
  doc.save(`Marker_${marker.index}_${safeName}.pdf`);
}

/** Generate and download all marker PDFs as separate files. */
export async function downloadAllMarkerPDFs(
  markers: MarkerPoint[],
  projectName: string,
  shareUrl: string
): Promise<void> {
  for (const marker of markers) {
    await downloadMarkerPDF(marker, projectName, shareUrl);
    await new Promise((r) => setTimeout(r, 300));
  }
}
