/**
 * Generate print-ready A4 PDFs for marker placement sheets.
 * Each PDF contains: branded marker image, QR code, placement instructions,
 * and coordinate details for on-site installation.
 */
import jsPDF from "jspdf";
import QRCode from "qrcode";
import { generateMarkerCanvas, type MarkerPoint } from "@/lib/generateMarkers";

const A4_W = 210; // mm
const A4_H = 297; // mm
const MARGIN = 15; // mm

const MARKER_COLORS: Record<string, { hex: string; name: string }> = {
  A: { hex: "#FF3B30", name: "Red" },
  B: { hex: "#34C759", name: "Green" },
  C: { hex: "#007AFF", name: "Blue" },
};

/**
 * Generate a single A4 marker PDF for one point.
 * Layout (top → bottom):
 *   - Header bar with project name + point label
 *   - Large marker image (centered, ~130 mm)
 *   - Coordinate details
 *   - QR code + share URL
 *   - Placement instructions footer
 */
export async function generateMarkerPDF(
  pointId: string,
  coords: MarkerPoint,
  projectName: string,
  shareUrl: string
): Promise<jsPDF> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const color = MARKER_COLORS[pointId] || MARKER_COLORS.A;
  const contentW = A4_W - MARGIN * 2;
  let y = MARGIN;

  // ── Header bar ──
  doc.setFillColor(color.hex);
  doc.rect(0, 0, A4_W, 18, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(projectName.toUpperCase(), MARGIN, 12);
  doc.text(`MARKER ${pointId}`, A4_W - MARGIN, 12, { align: "right" });

  y = 26;

  // ── Point label ──
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(`Point ${pointId} — ${coords.label || `Marker ${pointId}`}`, A4_W / 2, y, {
    align: "center",
  });
  y += 10;

  // ── Marker image ──
  const markerCanvas = generateMarkerCanvas(pointId, coords, projectName);
  const markerDataUrl = markerCanvas.toDataURL("image/png");
  const markerSize = 130; // mm square
  const markerX = (A4_W - markerSize) / 2;
  doc.addImage(markerDataUrl, "PNG", markerX, y, markerSize, markerSize);
  y += markerSize + 8;

  // ── Coordinates ──
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("PLACEMENT COORDINATES", A4_W / 2, y, { align: "center" });
  y += 6;

  doc.setFontSize(13);
  doc.setFont("courier", "bold");
  doc.setTextColor(40, 40, 40);
  doc.text(`X: ${coords.x}    Y: ${coords.y}    Z: ${coords.z}  (mm)`, A4_W / 2, y, {
    align: "center",
  });
  y += 10;

  // ── QR code ──
  const qrCanvas = document.createElement("canvas");
  await QRCode.toCanvas(qrCanvas, shareUrl, {
    width: 400,
    margin: 1,
    color: { dark: "#212121", light: "#FFFFFF" },
  });
  const qrDataUrl = qrCanvas.toDataURL("image/png");
  const qrSize = 32;
  const qrX = (A4_W - qrSize) / 2;
  doc.addImage(qrDataUrl, "PNG", qrX, y, qrSize, qrSize);
  y += qrSize + 4;

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(140, 140, 140);
  doc.text("Scan to view AR experience", A4_W / 2, y, { align: "center" });
  y += 4;
  doc.setFontSize(7);
  doc.text(shareUrl, A4_W / 2, y, { align: "center" });
  y += 8;

  // ── Instructions footer ──
  doc.setDrawColor(220, 220, 220);
  doc.line(MARGIN, y, A4_W - MARGIN, y);
  y += 5;

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(80, 80, 80);
  doc.text("PLACEMENT INSTRUCTIONS", MARGIN, y);
  y += 5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 100, 100);
  const instructions = [
    `1. Print this page at 100% scale (no fit-to-page). The marker must be actual size for accurate AR tracking.`,
    `2. Place this sheet at the coordinates shown above (X: ${coords.x}, Y: ${coords.y}, Z: ${coords.z} mm).`,
    `3. Ensure the marker is flat, well-lit, and unobstructed. Avoid reflective surfaces or glass overlays.`,
    `4. All three markers (A, B, C) must be placed before the AR experience can align the 3D model.`,
  ];
  instructions.forEach((line) => {
    const split = doc.splitTextToSize(line, contentW);
    doc.text(split, MARGIN, y);
    y += split.length * 3.5 + 1.5;
  });

  // ── Footer branding ──
  doc.setFontSize(6.5);
  doc.setTextColor(180, 180, 180);
  doc.text("Generated by Archi AR", A4_W / 2, A4_H - 8, { align: "center" });

  return doc;
}

/** Generate and trigger download of a single marker PDF. */
export async function downloadMarkerPDF(
  pointId: string,
  coords: MarkerPoint,
  projectName: string,
  shareUrl: string
): Promise<void> {
  const doc = await generateMarkerPDF(pointId, coords, projectName, shareUrl);
  const safeName = projectName.replace(/\s+/g, "_");
  doc.save(`Marker_${pointId}_${safeName}.pdf`);
}

/** Generate and download all marker PDFs (A, B, C) as separate files. */
export async function downloadAllMarkerPDFs(
  markerData: Record<string, MarkerPoint>,
  projectName: string,
  shareUrl: string
): Promise<void> {
  for (const [id, coords] of Object.entries(markerData)) {
    await downloadMarkerPDF(id, coords, projectName, shareUrl);
    // Small delay between downloads so browser doesn't block them
    await new Promise((r) => setTimeout(r, 300));
  }
}
